// This file is auto-generated by sync-backend-types.ts script
// DO NOT EDIT DIRECTLY

// From serverless/autocomplete/src/types.ts
// City data format for autocomplete
export interface CityAutocompleteData {
    header: string[];
    cities: string[][];
}

// City result type
export interface CityResult {
    wikidataId: string;
    name: string;
    countryWikidataId: string;
    countryName: string;
    countryCode: string;
    population?: number;
    populationDate?: string;
    latitude?: number;
    longitude?: number;
    officialWebsite?: string;
    socialMedia?: {
        twitter?: string;
        facebook?: string;
        instagram?: string;
        youtube?: string;
        linkedin?: string;
    };
    supersedes_duplicates?: string[];
    superseded_by?: string;
}

// Base request with common properties
interface BaseRequest {
    limit?: number;
}

// Specific request types for each action
export interface AutocompleteActionRequest extends BaseRequest {
    action: 'autocomplete';
    query: string;
}

export interface GetByQidActionRequest extends BaseRequest {
    action: 'getByQid';
    qid: string;
}

export interface BatchGetByQidActionRequest extends BaseRequest {
    action: 'batchGetByQid';
    qids: string[];
}

export interface BatchAutocompleteActionRequest extends BaseRequest {
    action: 'batchAutocomplete';
    queries: string[];
}

// Union type for all possible request types
export type AutocompleteRequest = 
    | AutocompleteActionRequest 
    | GetByQidActionRequest 
    | BatchGetByQidActionRequest 
    | BatchAutocompleteActionRequest;

// Response types
export interface AutocompleteResponse {
    results: CityResult[];
    message?: string;
}

export interface BatchAutocompleteResponse {
    results: Record<string, CityResult[]>;
    message?: string;
}

export interface BatchGetByQidResponse {
    results: CityResult[];
    notFound?: string[];
    message?: string;
}


// From serverless/public/src/types.ts
// City data format
export interface City {
    id: string;
    name: string;
    authenticationKeyDistributionChannels: {
        account: string;
        type: 'linkedin' | 'email';
        confidence: number;
    }[];
}

export interface GetPublicVotesRequest {
    action: 'getVotes';
    cityId?: string;
}

export interface GetPublicCitiesRequest {
    action: 'getCities';
}

export interface GetVotesResponse {
    // added here for allowing the backend types to be copied to the frontend VoteData is defined in votes/types.ts
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    votes: VoteData;
    message?: string;
}

export interface GetCitiesResponse {
    cities: Record<string, City>;
}

// Registration API Request/Response types
export interface RegisterRequest {
    action: 'register';
    cityData: City;
}

export interface RegisterResponse {
    message: string;
    city?: City;
    error?: string;
}


// From serverless/vote/src/types.ts
// Vote storage format in S3
export interface VoteAuthor {
    title: string;
    name: string;
    actingCapacity: 'individual' | 'representingCityAdministration';
}

export interface VoteEntry {
    time?: number;
    vote: 'Yes' | 'No' | 'Sign';
    author: VoteAuthor;
    associatedCityId?: string; // wikidataId
    organisationNameFallback?: string;
    externalVerificationSource?: string; // URL
}

export interface PollData {
    organisedBy?: string;
    URL?: string;
    type: 'poll' | 'jointStatement';
    votes: VoteEntry[];
    createdAt?: number;
}

export type VoteData = Record<string, PollData>;


// City data format
export interface City {
    id: string;
    name: string;
    population: number;
    country: string;
    lat: number;
    lon: number;
    authenticationKeyDistributionChannels: {
        account: string;
        type: 'linkedin' | 'email';
        confidence: number;
    }[];
}

// API Request/Response types
export interface ValidateTokenRequest {
    action: 'validateToken';
    token: string;
}

export interface VoteRequest {
    action: 'vote';
    cityId?: string;
    token: string;
    pollId: string;
    option: string;
    title: string;
    name: string;
    actingCapacity: 'individual' | 'representingCityAdministration';
}

export interface GetVotesRequest {
    action: 'getVotes';
    cityId?: string;
    token: string;
}

export interface GetCitiesRequest {
    action: 'getCities';
    token: string;
}

export interface CreatePollRequest {
    action: 'createPoll';
    token: string;
    pollId: string;
    documentUrl?: string;
    organisedBy?: string;
}

export interface GetUploadUrlRequest {
    action: 'getUploadUrl';
    pollId: string;
    token: string;
    fileHash: string; // Hash of the file contents (required)
}

// Internal interfaces used by the backend
export interface ValidateTokenParams {
    resolvedCity: City;
    token: string;
}

export interface VoteParams {
    cityId?: string;
    resolvedCity: City;
    token: string;
    pollId: string;
    option: string;
    title: string;
    name: string;
    actingCapacity: 'individual' | 'representingCityAdministration';
    externalVerificationSource?: string; // Platform that verified this vote
}

export interface CreatePollParams {
    resolvedCity: City;
    token: string;
    pollId: string;
    documentUrl?: string;
    organisedBy?: string;
}

export interface GetUploadUrlParams {
    resolvedCity: City;
    token: string;
    pollId: string;
    fileHash: string; // Hash of the file contents (required)
}

// API Response types
export interface ValidateTokenResponse {
    city: City;
    cityId: string;
    message?: string;
    details?: string;
}

export interface UploadAttachmentResponse {
    message: string;
    uploadUrl?: string;
    getUrl?: string;
    pollId?: string;
    details?: string;
}

export interface VoteResponse {
    message: string;
}

export interface GetVotesResponse {
    votes: VoteData;
    message?: string;
}

export interface GetCitiesResponse {
    cities: Record<string, City>;
}

export interface CreatePollResponse {
    message: string;
}


