// This file is auto-generated by sync-backend-types.ts script
// DO NOT EDIT DIRECTLY

// From serverless/autocomplete/src/types.ts
// City data format for autocomplete
export interface CityAutocompleteData {
    header: string[];
    cities: string[][];
}

// API Request/Response types
export interface AutocompleteRequest {
    action: 'autocomplete' | 'getByQid';
    query: string;
    qid?: string;
    limit?: number;
}

export interface AutocompleteResponse {
    results: {
        wikidataId: string;
        name: string;
        countryWikidataId: string;
        countryName: string;
        countryCode: string;
        population?: number;
        populationDate?: string;
        latitude?: number;
        longitude?: number;
        officialWebsite?: string;
        socialMedia?: {
            twitter?: string;
            facebook?: string;
            instagram?: string;
            youtube?: string;
            linkedin?: string;
        };
        supersedes_duplicates?: string[];
        superseded_by?: string;
    }[];
    message?: string;
}


// From serverless/public/src/types.ts
// Vote storage format in S3 (underscore added to prevent name collision in synced file)
export type VoteData_ = Record<string, Record<string, [number, string, {
    title: string;
    name: string;
    actingCapacity: 'individual' | 'representingCityAdministration';
}][]>>;

// City data format
export interface City {
    id: string;
    name: string;
    authenticationKeyDistributionChannels: {
        account: string;
        type: 'linkedin' | 'email';
        confidence: number;
    }[];
}

export interface GetPublicVotesRequest {
    action: 'getVotes';
    cityId?: string;
}

export interface GetPublicCitiesRequest {
    action: 'getCities';
}

export interface GetVotesResponse {
    votes: VoteData_;
    message?: string;
}

export interface GetCitiesResponse {
    cities: Record<string, City>;
}

// Registration API Request/Response types
export interface RegisterRequest {
    action: 'register';
    cityData: City;
}

export interface RegisterResponse {
    message: string;
    city?: City;
    error?: string;
}


// From serverless/vote/src/types.ts
// Vote storage format in S3
export type VoteData = Record<string, Record<string, [number, string, {
    title: string;
    name: string;
    actingCapacity: 'individual' | 'representingCityAdministration';
}][]>>;

// City data format
export interface City {
    id: string;
    name: string;
    population: number;
    country: string;
    lat: number;
    lon: number;
    authenticationKeyDistributionChannels: {
        account: string;
        type: 'linkedin' | 'email';
        confidence: number;
    }[];
}

// API Request/Response types
export interface ValidateTokenRequest {
    action: 'validateToken';
    token: string;
}

export interface VoteRequest {
    action: 'vote';
    cityId?: string;
    token: string;
    pollId: string;
    option: string;
    title: string;
    name: string;
    actingCapacity: 'individual' | 'representingCityAdministration';
}

export interface GetVotesRequest {
    action: 'getVotes';
    cityId?: string;
    token: string;
}

export interface GetCitiesRequest {
    action: 'getCities';
    token: string;
}

export interface CreatePollRequest {
    action: 'createPoll';
    token: string;
    pollId: string;
}

export interface UploadAttachmentRequest {
    action: 'uploadAttachment';
    token: string;
    pollId: string;
    attachmentId?: string;
}

// API Response types
export interface ValidateTokenResponse {
    city: City;
    cityId: string;
    message?: string;
    details?: string;
}

export interface UploadAttachmentResponse {
    message: string;
    attachmentUrl?: string;
    uploadUrl?: string;
    getUrl?: string;
    pollId?: string; // Added to return the formatted pollId for attachments
    details?: string;
}

export interface GetAttachmentUrlResponse {
    message: string;
    attachmentUrl?: string; // Direct URL to the attachment (no longer a presigned URL)
    details?: string;
}

export interface VoteResponse {
    message: string;
}

export interface GetVotesResponse {
    votes: VoteData;
    message?: string;
}

export interface GetCitiesResponse {
    cities: Record<string, City>;
}

export interface CreatePollResponse {
    message: string;
}


